version: '3.4'

services:
  api:
    build:
      context: ./api/.
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      NUM_THREADS: 2
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: ds_api
      PGUSER: admin
      PGPASSWORD: admin
    ports:
      - 3000:3000
    volumes:
      - ./api/:/api
      - /api/node_modules
    command: wait-for-it postgres:5432 -t 60 -- node app.js

  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules
    command: wait-for-it api:3000 -t 60 -- npm start

  postgres:
    image: postgres:latest
    environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: ds_api
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  pgadmin:
    image: crunchydata/crunchy-pgadmin4:centos7-9.6-1.3.0
    ports:
      - 5050:5050

volumes:
  dbdata:
    driver: local


